### PR TITLE
My first commit - MJ

### PR DESCRIPTION
**Pull request by Eriotek**
Pingi @AnalyzeAppPerformance/students

### CODE REVIEW

**Comment by partikus** [comment]
@Eriotek please rebase

**Comment by Eriotek** [comment]
ping @AnalyzeAppPerformance/students

**Comment by partikus** [comment]
@Eriotek rebase please

**Comment by Eriotek** [comment]
ping @AnalyzeAppPerformance/students

**Comment by Eriotek** [comment]
ping @AnalyzeAppPerformance/students

**Pull request merged**
