### PR TITLE
Some improvements 

### PR DESCRIPTION
**Pull request by partikus**

### CODE REVIEW

**Comment by partikus** [comment]
@AnalyzeAppPerformance/students @AnalyzeAppPerformance/core-team 
ping code review

**Comment by partikus** [comment]
@AnalyzeAppPerformance/students ping

**Comment by Eriotek** [comment]
:+1:

**Comment by kramar51** [comment]
:+1:

**Comment by ghost** [comment]
:+1:

**Comment by Cavantar** [comment]
:+1:

**Comment by bartekbrozek** [comment]
:+1:

**Comment by jhryniuk** [comment]
:+1:

**Comment by maxb931** [comment]
:+1:

**Comment by DamianTt** [comment]
:+1:

**Pull request merged**
