### PR TITLE
My first commit - jpadjasek

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by ghost** [comment]
ping @AnalyzeAppPerformance/students

**Comment by ghost** [comment]
@AnalyzeAppPerformance/students ping

**Comment by partikus** [comment]
@jpadjasek1 rebase please

**Comment by ghost** [comment]
@AnalyzeAppPerformance/students

**Comment by jhryniuk** [comment]
:+1:

**Comment by partikus** [comment]
@jpadjasek1 rebase please

**Pull request merged**
